Repository BC-MAY-21-ROR/proyecto-proy-t02, pull requests merged in 2021-08, with the labels that each got.

#14 add tailwind
  local_sales/Gemfile
  local_sales/Gemfile.lock
  local_sales/app/javascript/packs/application.js
  local_sales/app/javascript/stylesheets/application.scss
  local_sales/app/javascript/stylesheets/tailwind.config.js
  local_sales/app/views/layouts/application.html.erb
  local_sales/package.json
  local_sales/postcss.config.js
  local_sales/yarn.lock
Labels: mentor review required, review required

#24 Enhancement#23/unit test setup
  local_sales/.rspec
  local_sales/Gemfile
  local_sales/Gemfile.lock
  local_sales/spec/rails_helper.rb
  local_sales/spec/spec_helper.rb
  local_sales/spec/support/factory_bot.rb
Labels: ready for review

#25 creating models and migrations
  local_sales/app/models/category.rb
  local_sales/app/models/company.rb
  local_sales/app/models/offer.rb
  local_sales/app/models/product.rb
  local_sales/app/models/provider.rb
  local_sales/db/migrate/20210809184403_create_companies.rb
  local_sales/db/migrate/20210809184657_create_products.rb
  local_sales/db/migrate/20210809184734_create_categories.rb
  local_sales/db/migrate/20210809184808_create_offers.rb
  local_sales/db/migrate/20210809184827_create_providers.rb
Labels: mentor review required, review required

#28 Add authentication user
  local_sales/Gemfile
  local_sales/app/controllers/users/confirmations_controller.rb
  local_sales/app/controllers/users/omniauth_callbacks_controller.rb
  local_sales/app/controllers/users/passwords_controller.rb
  local_sales/app/controllers/users/registrations_controller.rb
  local_sales/app/controllers/users/sessions_controller.rb
  local_sales/app/controllers/users/unlocks_controller.rb
  local_sales/app/models/user.rb
  local_sales/app/views/devise/confirmations/new.html.erb
  local_sales/app/views/devise/mailer/confirmation_instructions.html.erb
  local_sales/app/views/devise/mailer/email_changed.html.erb
  local_sales/app/views/devise/mailer/password_change.html.erb
  local_sales/app/views/devise/mailer/reset_password_instructions.html.erb
  local_sales/app/views/devise/mailer/unlock_instructions.html.erb
  local_sales/app/views/devise/passwords/edit.html.erb
  local_sales/app/views/devise/passwords/new.html.erb
  local_sales/app/views/devise/registrations/edit.html.erb
  local_sales/app/views/devise/registrations/new.html.erb
  local_sales/app/views/devise/sessions/new.html.erb
  local_sales/app/views/devise/shared/_error_messages.html.erb
  local_sales/app/views/devise/shared/_links.html.erb
  local_sales/app/views/devise/unlocks/new.html.erb
  local_sales/config/initializers/devise.rb
  local_sales/config/locales/devise.en.yml
  local_sales/config/routes.rb
  local_sales/db/migrate/20210810063747_devise_create_users.rb
  local_sales/db/schema.rb
  local_sales/test/fixtures/users.yml
  local_sales/test/models/user_test.rb
Labels: ready for review

#33 Feature#21/login design
  local_sales/Gemfile
  local_sales/Gemfile.lock
  local_sales/app/views/devise/sessions/new.html.erb
  local_sales/app/views/layouts/application.html.erb
  local_sales/db/schema.rb
Labels: mentor review required

#36 config for heroku deployment
  README.md
  local_sales/Gemfile.lock
  local_sales/config/application.rb
  local_sales/config/database.yml
Labels: mentor review required

#35 Enhancement#30/code analyzer
  README.md
  local_sales/.rubocop.yml
  local_sales/Gemfile
  local_sales/Gemfile.lock
  local_sales/badges/app/rubycritic_badge_score.svg
  local_sales/badges/spec/rubycritic_badge_score.svg
  local_sales/lib/tasks/code_quality.rake
Labels: mentor review required

#34 Enhancement#26/model tests
  local_sales/Gemfile
  local_sales/Gemfile.lock
  local_sales/app/models/category.rb
  local_sales/app/models/company.rb
  local_sales/app/models/offer.rb
  local_sales/app/models/product.rb
  local_sales/app/models/provider.rb
  local_sales/db/migrate/20210809184403_create_companies.rb
  local_sales/db/migrate/20210812080533_add_category_ref_to_companies.rb
  local_sales/db/migrate/20210812081301_add_company_ref_to_providers.rb
  local_sales/db/migrate/20210812081351_add_company_ref_to_products.rb
  local_sales/db/migrate/20210812085229_create_join_table_offer_product.rb
  local_sales/spec/models/category_spec.rb
  local_sales/spec/models/company_spec.rb
  local_sales/spec/models/offer_spec.rb
  local_sales/spec/models/product_spec.rb
  local_sales/spec/models/provider_spec.rb
  local_sales/test/application_system_test_case.rb
  local_sales/test/channels/application_cable/connection_test.rb
  local_sales/test/controllers/.keep
  local_sales/test/fixtures/files/.keep
  local_sales/test/fixtures/users.yml
  local_sales/test/helpers/.keep
  local_sales/test/integration/.keep
  local_sales/test/mailers/.keep
  local_sales/test/models/.keep
  local_sales/test/models/user_test.rb
  local_sales/test/system/.keep
  local_sales/test/test_helper.rb
Labels: mentor review required

#38 CRUD
  local_sales/app/controllers/companies_controller.rb
  local_sales/app/models/company.rb
  local_sales/app/views/companies/_form.html.erb
  local_sales/app/views/companies/edit.html.erb
  local_sales/app/views/companies/index.html.erb
  local_sales/app/views/companies/new.html.erb
  local_sales/bin/bundle
  local_sales/bin/rails
  local_sales/bin/rake
  local_sales/bin/setup
  local_sales/bin/spring
  local_sales/bin/webpack
  local_sales/bin/webpack-dev-server
  local_sales/bin/yarn
  local_sales/config/routes.rb
  local_sales/db/schema.rb
  local_sales/postcss.config.js
Labels: mentor review required

#44 Feature#41/products crud
  local_sales/app/controllers/products_controller.rb
  local_sales/app/views/products/_form.html.erb
  local_sales/app/views/products/edit.html.erb
  local_sales/app/views/products/index.html.erb
  local_sales/app/views/products/new.html.erb
  local_sales/app/views/products/show.html.erb
  local_sales/config/routes.rb
Labels: mentor review required

#43 Offer's CRUD structure
  local_sales/.env.example
  local_sales/app/controllers/offers_controller.rb
  local_sales/app/models/offer.rb
  local_sales/app/models/product.rb
  local_sales/app/views/offers/_form.html.erb
  local_sales/app/views/offers/_offer.json.jbuilder
  local_sales/app/views/offers/edit.html.erb
  local_sales/app/views/offers/index.html.erb
  local_sales/app/views/offers/index.json.jbuilder
  local_sales/app/views/offers/new.html.erb
  local_sales/app/views/offers/show.html.erb
  local_sales/app/views/offers/show.json.jbuilder
  local_sales/badges/spec/rubycritic_badge_score.svg
  local_sales/config/database.yml
  local_sales/config/routes.rb
  local_sales/db/schema.rb
Labels: mentor review required

#45 Feature#37/administrator crud
  local_sales/.rubocop.yml
  local_sales/Gemfile.lock
  local_sales/app/controllers/administrators_controller.rb
  local_sales/app/models/user.rb
  local_sales/app/queries/users_query.rb
  local_sales/app/views/administrators/_form.html.erb
  local_sales/app/views/administrators/edit.html.erb
  local_sales/app/views/administrators/index.html.erb
  local_sales/app/views/administrators/new.html.erb
  local_sales/app/views/administrators/show.html.erb
  local_sales/app/views/devise/sessions/new.html.erb
  local_sales/badges/app/rubycritic_badge_score.svg
  local_sales/config/application.rb
  local_sales/config/routes.rb
  local_sales/db/migrate/20210815161018_add_role_to_users.rb
  local_sales/db/migrate/20210815172100_add_name_to_users.rb
Labels: mentor review required

#60 update and restructure of erm diagram
  .github/docs/images/ERM_diagram.png
Labels: mentor review required

#63 Categories CRUD and views without design
  local_sales/app/controllers/categories_controller.rb
  local_sales/app/views/categories/_form.html.erb
  local_sales/app/views/categories/edit.html.erb
  local_sales/app/views/categories/index.html.erb
  local_sales/app/views/categories/new.html.erb
  local_sales/config/routes.rb
Labels: mentor review required

#69 changing companies views design
  local_sales/app/views/companies/_form.html.erb
  local_sales/app/views/companies/edit.html.erb
  local_sales/app/views/companies/index.html.erb
  local_sales/app/views/companies/new.html.erb
Labels: mentor review required

#77 Township's crud system and design
  local_sales/app/controllers/townships_controller.rb
  local_sales/app/views/townships/_form.html.erb
  local_sales/app/views/townships/edit.html.erb
  local_sales/app/views/townships/index.html.erb
  local_sales/app/views/townships/new.html.erb
  local_sales/config/routes.rb
Labels: mentor review required

#78 Town's crud system and design
  local_sales/app/controllers/towns_controller.rb
  local_sales/app/views/towns/_form.html.erb
  local_sales/app/views/towns/edit.html.erb
  local_sales/app/views/towns/index.html.erb
  local_sales/app/views/towns/new.html.erb
  local_sales/config/routes.rb
Labels: mentor review required

#83 CRUD categories views
  local_sales/app/views/categories/_form.html.erb
  local_sales/app/views/categories/edit.html.erb
  local_sales/app/views/categories/index.html.erb
  local_sales/app/views/categories/new.html.erb
Labels: mentor review required

#84 Feature#71/sidebar design
  local_sales/app/assets/stylesheets/application.css
  local_sales/app/controllers/products_controller.rb
  local_sales/app/javascript/packs/sidebar.js
  local_sales/app/views/devise/sessions/new.html.erb
  local_sales/app/views/layouts/_sidebar.html.erb
  local_sales/app/views/layouts/application.html.erb
Labels: mentor review required
